[package]
name = "oasis-runtime-sdk-macros"
version = "0.1.0"
authors = ["Oasis Protocol Foundation <info@oasisprotocol.org>"]
edition = "2018"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
Inflector = "0.11.4"
darling = "0.13.0"
proc-macro2 = "1.0.27"
quote = "1.0.9"
syn = "1.0.74"

[dev-dependencies]
diff = "0.1.12"
syn = { version = "1.0.74", features = ["extra-traits"] }
